### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by marcolanfranchi** [philtgun/streamlit-audio-plot#2]
There are issues installing the package. After running `pip install streamlit-audio-plot`, I got the following error:

**ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/e1/f7/564c82f032b7bd3a063a189e21eca3da40e8ae4354dad56b82f4999745f0/streamlit_audio_plot-0.1.1-py3-none-any.whl.metadata (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x104746450>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))**

**Comment by philtgun** [comment]
This doesn't seem like an issue with this package, seems more like the environment issue (e.g. [thread](https://stackoverflow.com/questions/55688358/how-to-fix-could-not-install-packages-due-to-an-environmenterror-httpsconnecti)). Let me know if you can indeed install other packages successfully (pypi server can be contacted), but only this package is failing. In that case, please provide more details about your environment.

**Comment by philtgun** [comment]
@marcolanfranchi feel free to reopen the issue if the problem persists
